model_name: cbow

dataset: Histaware
data_dir: ../data/fuel/tm_87/*.csv
train_batch_size: 32
val_batch_size: 32
shuffle: True
validation_split: 0.2
random_seed: 1234

optimizer: Adam
learning_rate: 0.025
epochs: 10
train_steps: 
val_steps: 

checkpoint_frequency: 
model_dir: ../weights/cbow_histaware_87
